/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGithubGraphRouteImport } from './routes/api.github-graph'
import { Route as ApiAgentRouteImport } from './routes/api.agent'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubGraphRoute = ApiGithubGraphRouteImport.update({
  id: '/api/github-graph',
  path: '/api/github-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/github-graph': typeof ApiGithubGraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/github-graph': typeof ApiGithubGraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/github-graph': typeof ApiGithubGraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/terminal' | '/api/agent' | '/api/github-graph'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/terminal' | '/api/agent' | '/api/github-graph'
  id: '__root__' | '/' | '/terminal' | '/api/agent' | '/api/github-graph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TerminalRoute: typeof TerminalRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiGithubGraphRoute: typeof ApiGithubGraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-graph': {
      id: '/api/github-graph'
      path: '/api/github-graph'
      fullPath: '/api/github-graph'
      preLoaderRoute: typeof ApiGithubGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TerminalRoute: TerminalRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiGithubGraphRoute: ApiGithubGraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
